root: true
extends: wopian-react
parserOptions:
  sourceType: module
env:
  browser: true
rules:
  # Allow paren-less arrow functions
  arrow-parens: 0
  # Allow async-await
  generator-star-spacing: 0
